### ISSUE TITLE
youtubei 0.0.1-rc.25 fixed with DMP 8.2.0

### ISSUE THREAD

**Issue by ka0sdev** [MeridianGH/suitbot#10]
Update package.json, removed resolutions and changed DMP version to 8.2.0. 
youtubei 0.0.1-rc.25 httpsOptions variable renamed to requestOptions - DMP updated variables. 

`{
  "name": "suitbot",
  "version": "1.0.0",
  "description": "A lightweight music and general purpose bot, that uses slash commands and buttons to be as user-friendly as possible! ",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "engines": {
    "node": "16.x"
  },
  "author": "Meridian",
  "license": "Apache-2.0",
  "dependencies": {
    "@discordjs/builders": "^0.6.0",
    "@discordjs/rest": "^0.1.0-canary.0",
    "body-parser": "^1.19.0",
    "discord-api-types": "^0.23.1",
    "discord-music-player": "^8.2.0",
    "discord.js": "^13.1.0",
    "ejs": "^3.1.6",
    "ejs-lint": "^1.2.1",
    "express": "^4.17.1",
    "express-session": "^1.17.2",
    "memorystore": "^1.6.6",
    "node-fetch": "^3.0.0",
    "passport": "^0.4.1",
    "passport-discord": "^0.1.4",
    "standard": "*"
  }
}`

**Comment by MeridianGH** [comment]
Thanks for the notice, fixed in 281e0cd139d676c3c732c5d315fb921b5b091b4f.
