### ISSUE TITLE
Ignoring uncaught exception: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.

### ISSUE THREAD

**Issue by vinzy2** [MeridianGH/suitbot#17]
have this error may need to be fixed

```Ignoring uncaught exception: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted. | WebSocketManager.js:250:15```

**Comment by MeridianGH** [comment]
You probably have the `Presence Intent` in the Discord Developer Portal deactivated. Can you check?

**Comment by vinzy2** [comment]
yes you are right i did have that disables as i think that is the default

**Comment by MeridianGH** [comment]
Turn it on and it will work just fine.

**Comment by lucadsign** [comment]
> have this error may need to be fixed
> 
> `Ignoring uncaught exception: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted. | WebSocketManager.js:250:15`

can you close now if you got the answer?

**Comment by futureengco** [comment]
> have this error may need to be fixed
> 
> `Ignoring uncaught exception: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted. | WebSocketManager.js:250:15`
